### ISSUE TITLE
Add tailwind-config as a shared package

### ISSUE THREAD

**Issue by ATLAS2002** [ATLAS2002/resonatejs#3]
> [!NOTE]
> - Inside the `base` directory, create a new directory `tailwind-config`.
> - Create a `tailwind.config.ts` and `postcss.config.ts` file.
> - Configure all the base properties (set accurate paths in `content`).
> - Extend tailwind and postcss config files in other workspaces from the base tailwind-config package.

> [!TIP]
> - Use pnpm to install the packages: `tailwindcss`, `postcss` and `autoprefixer`.
> - Instead of creating the config files, run this command instead: `pnpx tailwindcss init -p`.
> - If the files are in **.js**, change them to **.ts**, and use proper types.

**Comment by MaruthiSingh** [comment]
I would like to work on that issue under JWOC

**Comment by ATLAS2002** [comment]
> I would like to work on that issue under JWOC

Sure, I have assigned it to you. Happy Coding ⭐

**Comment by MaruthiSingh** [comment]
I facing some error in my system so can you assign this to anyone else.

**Comment by vermaanurag1532** [comment]
please assign it to me i can do this for you

**Comment by ATLAS2002** [comment]
> please assign it to me i can do this for you

Hi @vermaanurag1532 , this issue is a part of an open source program - JWOC. And only the registered mentees can be assigned this issue. If you are already participating in JWOC and want to be assigned this issue, then you have mention that in the comment.

**Comment by vermaanurag1532** [comment]
yeah i want to contribute under jwoc and i am a registered mentee in this open source program

**Comment by ATLAS2002** [comment]
> yeah i want to contribute under jwoc and i am a registered mentee in this open source program

After successfully merging and closing this issue, I can assign you the later issues. You do have limited time for each of these issues so I will wish you luck.

**Comment by ATLAS2002** [comment]
Quick reminder @vermaanurag1532 , the time is almost up. If you are still working on this then please let me know about the progress, if you are facing an issue I'll be more than happy to help.

**Comment by Jenis07** [comment]
Can you please assign me this issue under JWOC?

**Comment by Jenis07** [comment]
![image](https://github.com/ATLAS2002/resonatejs/assets/100338684/a8652648-f390-4bcb-9e37-3d36802f40b5)
i got this error when i am installing the tailwindcss package using pnpm..

**Comment by ATLAS2002** [comment]
Just run pnpm add -D tailwindcss postcss autoprefixer.

**Comment by Jenis07** [comment]
![image](https://github.com/ATLAS2002/resonatejs/assets/100338684/9396b06b-f272-4c38-8df6-066c13669a5f)
i am still getting error..

**Comment by ATLAS2002** [comment]
Try running the command without the -w flag.

**Comment by ATLAS2002** [comment]
@Jenis07 don't install tailwind in root, first create a folder "tailwind-config" inside the base folder. Then cd into the folder and install the packages there

**Comment by Jenis07** [comment]
![image](https://github.com/ATLAS2002/resonatejs/assets/100338684/dd2cf238-78ca-405d-af0d-cd60f2a4a7fd)
as you told that i have do that..

**Comment by ATLAS2002** [comment]
> ![image](https://private-user-images.githubusercontent.com/100338684/299264427-dd2cf238-78ca-405d-af0d-cd60f2a4a7fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODk5NjQsIm5iZiI6MTcwNjA4OTY2NCwicGF0aCI6Ii8xMDAzMzg2ODQvMjk5MjY0NDI3LWRkMmNmMjM4LTc4Y2EtNDA1ZC1hZjBkLWNkNjBmMmE0YTdmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQwOTQ3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDkwMzIwNWQ3ZWY0NzkyNDM0Y2U2OGU3MDhhNjYyMmY5ZDIxNmU1MTg4N2E5NGY3NjEyMGNlYWQ3MjQ5YTZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lrLaPduC4WtgVZvO_p0zz0SWx8izUuO8ru6X2q1KygI) as you told that i have do that..

Okay I have figured out the error,
- create package.json inside /base/tailwind-config:
```
{
  "name": "@repo/tailwind-config",
  "version": "0.0.0",
  "private": true,
}
```
- run `pnpm install` from the root. 
- then run this: `pnpm add -D tailwindcss autoprefixer postcss --filter=@repo/tailwind-config`

After that you will have the necessary packages installed in the `/tailwind-config` directory.

**Comment by ATLAS2002** [comment]
Also can you submit a PR within today? The duration for an easy issue is 1 day and we have already crossed that limit.

**Comment by Jenis07** [comment]
I have added the package.json file and try to run the command.
![image](https://github.com/ATLAS2002/resonatejs/assets/100338684/3d09fd52-d243-4347-a296-5a2316a1c254)
but it shows this error.

**Comment by ATLAS2002** [comment]
![Screenshot 2024-01-24 162759](https://github.com/ATLAS2002/resonatejs/assets/123821746/e221c622-f36a-4373-acc4-01cb1a3016b8)
Because this package does not exist, remove it from the dependencies and run pnpm install again

**Comment by Jenis07** [comment]
Yeah that's successfully installed

**Comment by ATLAS2002** [comment]
> Yeah that's successfully installed

@Jenis07 this issue is open for quite some time. So I need you to respond to this, else I will have to close this issue.

**Comment by Anushkabh** [comment]
@ATLAS2002  I WANT TO WORK ON THIS ISSUE UNDER JWOC.. KINDLY ASSIGN

**Comment by ATLAS2002** [comment]
> @ATLAS2002 I WANT TO WORK ON THIS ISSUE UNDER JWOC.. KINDLY ASSIGN

Let me know if there are any issues with the setup
